title: "AA DigitalWorks"
email: info@aadigitalworks.com
description: "Insights, tips and latest trends in digital marketing, SEO, and web development"
baseurl: "" 
url: "https://www.aadigitalworks.com"


markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# For Jekyll 3.x compatibility (use 'gems' instead of 'plugins')
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from