name: New Post Dispatch

on:
  repository_dispatch:
    types: [new-post]

jobs:
  create-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Markdown post
        run: |
          mkdir -p _posts
          FILENAME="_posts/$(date +'%Y-%m-%d')-${GITHUB_EVENT_CLIENT_PAYLOAD_SLUG}.md"
          echo "$GITHUB_EVENT_CLIENT_PAYLOAD_BODY" > "$FILENAME"
        env:
          GITHUB_EVENT_CLIENT_PAYLOAD_BODY: ${{ github.event.client_payload.body }}
          GITHUB_EVENT_CLIENT_PAYLOAD_SLUG: ${{ github.event.client_payload.slug }}
