name: Create Post

on:
  repository_dispatch:
    types: [new-post]

jobs:
  create-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create _posts folder
        run: mkdir -p _posts

      - name: Create post file
        run: |
          echo "${{ github.event.client_payload.body }}" > _posts/${{ github.event.client_payload.date }}-${{ github.event.client_payload.slug }}.md
        shell: bash

      - name: Commit & push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "AA DigitalWorks Bot"
          git config user.email "aadigitalworkss@gmail.com"
          git add _posts/*
          git commit -m "New post: ${{ github.event.client_payload.title }}" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
